const levels = [
    [
        [RED, EMPTY, GREEN, EMPTY, YELLOW],
        [EMPTY, EMPTY, BLUE, EMPTY, ORANGE],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [EMPTY, GREEN, EMPTY, YELLOW, EMPTY],
        [EMPTY, RED, BLUE, ORANGE, EMPTY]
    ],

    [
        [GREEN, RED, EMPTY, EMPTY, RED],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [EMPTY, EMPTY, EMPTY, ORANGE, GREEN],
        [ORANGE, EMPTY, EMPTY, BLUE, YELLOW],
        [BLUE, EMPTY, YELLOW, EMPTY, EMPTY],
    ],

    [
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [EMPTY, BLUE, ORANGE, EMPTY, ORANGE, RED],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, BLUE],
        [EMPTY, EMPTY, EMPTY, EMPTY, RED, GREEN],
        [GREEN, YELLOW, EMPTY, EMPTY, YELLOW, EMPTY],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
    ],

    [
        [EMPTY, EMPTY, EMPTY, EMPTY, GREEN, EMPTY, CYAN],
        [EMPTY, CYAN, EMPTY, EMPTY, EMPTY, EMPTY, ORANGE],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [EMPTY, EMPTY, YELLOW, RED, EMPTY, EMPTY, RED],
        [EMPTY, EMPTY, EMPTY, BLUE, EMPTY, EMPTY, BLUE],
        [EMPTY, ORANGE, YELLOW, PINK, EMPTY, EMPTY, EMPTY],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, GREEN, PINK],
    ],

    [
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY],
        [EMPTY, GREEN, EMPTY, EMPTY, EMPTY, YELLOW, EMPTY],
        [EMPTY, EMPTY, YELLOW, EMPTY, EMPTY, BLUE, RED],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, PINK],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ORANGE, CYAN],
        [PINK, RED, GREEN, BLUE, EMPTY, EMPTY, EMPTY],
        [EMPTY, EMPTY, EMPTY, EMPTY, EMPTY, ORANGE, CYAN]
    ]
]